gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 6/6 items."}]}
give @p we:wedges_pot
give @p we:white_chocolate
give @p we:yeast
give @p we:ketchup
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
#give @p we:
gamerule sendcommandfeedback true