gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 2/6 items."}]}
give @p we:icecream_toffee
give @p we:icecream_vanilla
give @p we:icecrush_apple
give @p we:icecrush_apple_raspberry
give @p we:icecrush_berry
give @p we:icecrush_grape
give @p we:icecrush_lemon
give @p we:icecrush_melon
give @p we:icecrush_mixed_fruit
give @p we:icecrush_strawberry
give @p we:icecrush_orange
give @p we:juice_apple
give @p we:juice_berry
give @p we:juice_grape
give @p we:juice_lemon
give @p we:juice_mixed_fruit
give @p we:juice_orange
give @p we:juice_strawberry
give @p we:juice_tomato
give @p we:milkshake_banana
give @p we:milkshake_chocolate
give @p we:milkshake_strawberry
give @p we:pie_apple
give @p we:pie_apple_raspberry
give @p we:pie_base
give @p we:pie_berry
give @p we:pie_cheese
give @p we:pie_chicken
give @p we:pie_chocolate
give @p we:pie_golden_apple
give @p we:pie_lemon
give @p we:pie_plum
give @p we:pie_pork
give @p we:pie_steak
give @p we:pie_strawberry
give @p we:pie_toffee
gamerule sendcommandfeedback true