gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 1/6 items."}]}
give @p we:beer
give @p we:bottled_beer
give @p we:bottled_cider
give @p we:bottled_red_wine
give @p we:bottled_white_wine
give @p we:cider
give @p we:red_wine
give @p we:white_wine
give @p we:americano
give @p we:cappuccino
give @p we:hot_cocoa
give @p we:hot_coffee
give @p we:hot_tea
give @p we:macchiato
give @p we:mocha
give @p we:donut_chocolate
give @p we:donut_coffee
give @p we:donut_golden
give @p we:donut_iced
give @p we:donut_pink_ice
give @p we:donut_plain
give @p we:donut_strawberry
give @p we:donut_toffee
give @p we:banana
give @p we:grape
give @p we:lemon
give @p we:olives
give @p we:orange
give @p we:plum
give @p we:raspberry
give @p we:strawberry
give @p we:tomato
give @p we:icecream_banana
give @p we:icecream_chocolate
give @p we:icecream_cone
give @p we:icecream_strawberry
gamerule sendcommandfeedback true