gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 4/6 items."}]}
give @p we:coconut_milk
give @p we:cooked_bacon
give @p we:cooked_bat_meat
give @p we:cooked_hotdog_sausage
give @p we:cooked_sausage
give @p we:cornflour
give @p we:cream_carton
give @p we:custard
give @p we:cut_bread
give @p we:cut_fries
give @p we:dark_chocolate
give @p we:dough
give @p we:flour
give @p we:fried_egg
give @p we:fried_squid
give @p we:fries
give @p we:gelatin
give @p we:hamburger
give @p we:hamburger_patty
give @p we:hops
give @p we:hotdog
give @p we:hotdog_bun
give @p we:hotdog_sausage
give @p we:ice_bowl
give @p we:kebab
give @p we:milk_carton
give @p we:milk_chocolate
give @p we:muffin_bun
give @p we:noodles
give @p we:oil
give @p we:onigiri
give @p we:orange_jelly
give @p we:pancakes
give @p we:pasta
give @p we:pink_cupcake
give @p we:pitta_bread
gamerule sendcommandfeedback true