gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 5/6 items."}]}
give @p we:pizza
give @p we:pizza_base
give @p we:popcorn
give @p we:popcorn_bucket
give @p we:ramen_noodles
give @p we:raw_hamburger_patty
give @p we:raw_sausage
give @p we:raw_squid
give @p we:raw_veganburger_patty
give @p we:raw_wedges
give @p we:rice
give @p we:rice_pudding
give @p we:round_cheese
give @p we:salt
give @p we:sashimi
give @p we:sausage_egg_muffin
give @p we:sausage_egg_sandwich
give @p we:spaghetti
give @p we:sparkling_water_bucket
give @p we:strawberry_jelly
give @p we:sub_bun
give @p we:sushi
give @p we:taco
give @p we:tea_leaves
give @p we:toast
give @p we:toffee
give @p we:toffee_latte
give @p we:tomato_puree
give @p we:tortilla
give @p we:turkish_delight
give @p we:vanilla_extract
give @p we:vanilla_latte
give @p we:vanilla_pod
give @p we:veganburger
give @p we:veganburger_patty
give @p we:waffle
gamerule sendcommandfeedback true