gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 3/6 items."}]}
give @p we:smoothie_banana
give @p we:smoothie_berry
give @p we:smoothie_grape
give @p we:smoothie_mixed_fruit
give @p we:smoothie_raspberry
give @p we:smoothie_strawberry
give @p we:soda_apple
give @p we:soda_berry
give @p we:soda_grape
give @p we:soda_lemon
give @p we:soda_orange
give @p we:soda_strawberry
give @p we:corn_on_cob
give @p we:gherkin
give @p we:lettuce
give @p we:onion
give @p we:pickles
give @p we:bacon
give @p we:bacon_egg_muffin
give @p we:bacon_egg_sandwich
give @p we:bat_meat
give @p we:beef_sub
give @p we:blue_cupcake
give @p we:bread_loaf
give @p we:breakfast_sub
give @p we:burger_bun
give @p we:burrito
give @p we:butter
give @p we:cereal
give @p we:cheese_bucket
give @p we:cheese_toastie
give @p we:cheese_wedge
give @p we:chicken_fajita
give @p we:chicken_select
give @p we:chicken_sub
give @p we:coconut_meat
gamerule sendcommandfeedback true