gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all Ingredient items."}]}
give @s we:butter
give @s we:cheese_wedge
give @s we:cornflour
give @s we:cream_carton
give @s we:cut_fries
give @s we:flour
give @s we:gelatin
give @s we:ketchup
give @s we:milk_carton
give @s we:noodles
give @s we:oil
give @s we:pasta
give @s we:pickles
give @s we:raw_wedges
give @s we:round_cheese
give @s we:salt
give @s we:starch
give @s we:tomato_puree
give @s we:vanilla_extract
give @s we:yeast
give @s we:beer_glass
give @s we:beverage_cup
give @s we:bottle
give @s we:carton
give @s we:chicken_select_box
give @s we:empty_icecrush_glass
give @s we:empty_tumbler_glass
give @s we:fry_wrapper
give @s we:hot_beverage_cup
give @s we:icing
give @s we:jar
give @s we:soda_can_empty
give @s we:sub_wrapper
give @s we:wine_glass
#give @s we:
#give @s we:
gamerule sendcommandfeedback true