gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all item items."}]}
give @p we:beer_glass
give @p we:beverage_cup
give @p we:bottle
give @p we:carton
give @p we:chicken_select_box
give @p we:cream_carton
give @p we:empty_icecrush_glass
give @p we:empty_popcorn_bucket
give @p we:empty_tumbler_glass
give @p we:empty_wedges_pot
give @p we:fry_wrapper
give @p we:hot_beverage_cup
give @p we:icing
give @p we:jar
give @p we:pizza_box_opened
give @p we:recipe_book
give @p we:soda_can_empty
give @p we:starch
give @p we:sub_wrapper
give @p we:wine_glass
gamerule sendcommandfeedback true